"""add cost per day and cost per hour to jobs positions

Revision ID: 0e248c990cb5
Revises: 66ec44cfdc60
Create Date: 2025-03-13 18:25:56.543718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e248c990cb5'
down_revision: Union[str, None] = '66ec44cfdc60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('championship_assignments', 'job_position_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_championship_assignments_id'), 'championship_assignments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_championship_assignments_id'), table_name='championship_assignments')
    op.alter_column('championship_assignments', 'job_position_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
