"""add cost per day and cost per hour to jobs positions

Revision ID: dfa2a18e7c98
Revises: 0e248c990cb5
Create Date: 2025-03-13 18:28:49.739897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfa2a18e7c98'
down_revision: Union[str, None] = '0e248c990cb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # 1. Añades la columna como NULLABLE
    op.add_column('job_positions', sa.Column('cost_per_day', sa.Float(), nullable=True))

    # 2. Asignas valores a las filas ya existentes
    op.execute("UPDATE job_positions SET cost_per_day = 0")

    # 3. La cambias a NOT NULL
    op.alter_column('job_positions', 'cost_per_day', nullable=False)

    # 4. Si quieres, haces lo mismo para cost_per_hour
    op.add_column('job_positions', sa.Column('cost_per_hour', sa.Float(), nullable=True))
    op.execute("UPDATE job_positions SET cost_per_hour = 0")
    op.alter_column('job_positions', 'cost_per_hour', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_positions', 'cost_per_hour')
    op.drop_column('job_positions', 'cost_per_day')
    # ### end Alembic commands ###
